"""
Build CIRIquant-based BSJ and FSJ count matrices for the 7 PSD58 samples.

Universe construction:
  - per-sample consensus = circRNA detected by BOTH CIRCexplorer2 AND CIRIquant
    in that sample (BED file overlap on circ_id)
  - circRNA enters the universe if it is consensus-detected in >=1 sample
  - abundance filter: >= 2 CIRIquant BSJ reads in >= 2 samples
  (NO CE2 abundance filter — replaces the CE2-abundance criterion used in
   earlier analyses)

Counts: from the CIRIquant GTF (bsj and fsj attributes per circ_id).
Annotation: joined from FinalAnalysis/RESULTS/01_circRNA_DE/circRNA_annotation.tsv
            (regenerated by build_circRNA_annotation.py for reproducibility).
"""
import os
import re
import pandas as pd
from pathlib import Path

BASE   = Path("/Volumes/share/mnt/Scratch/PROJECTS/JW_Katana/circRBP_pilot/NF_LAUNCH_circrna_230420/results/circrna_discovery")
ANNOT  = Path("/Volumes/share/mnt/Scratch/PROJECTS/JW_Katana/circRBP_pilot/IV/ForPublication/FinalAnalysis/RESULTS/01_circRNA_DE/circRNA_annotation.tsv")
OUTDIR = Path("/Volumes/share/mnt/Scratch/PROJECTS/JW_Katana/circRBP_pilot/IV/ForPublication/FinalAnalysis/RESULTS/01_circRNA_DE")
OUTDIR.mkdir(parents=True, exist_ok=True)

SAMPLES = [
    "5_gHnrnpM_PSD5_S20","6_gHnrnpM_PSD5_S21","7_gHnrnpM_PSD8_S22",
    "9_gNEG4_PSD5_S24","11_gNEG4_PSD8_S3","12_gNEG4_PSD5_S4","13_gNEG4_PSD8_S5",
]

def parse_ce2_ids(path):
    s = set()
    if not os.path.exists(path):
        return s
    with open(path) as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 4:
                s.add(p[3])
    return s

def parse_ciri_ids(path):
    s = set()
    if not os.path.exists(path):
        return s
    with open(path) as f:
        for line in f:
            p = line.strip().split("\t")
            if len(p) >= 4:
                s.add(p[3])
    return s

def bed_to_gtf_key(c):
    """BED-style circRNA ID (0-based start) -> CIRIquant GTF circ_id (1-based)."""
    chrom, rest = c.split(":", 1)
    coords, _ = rest.rsplit(":", 1)
    s, e = coords.split("-")
    return f"{chrom}:{int(s)+1}|{e}"

re_circ = re.compile(r'circ_id "([^"]+)"')
re_bsj  = re.compile(r'bsj ([0-9.]+)')
re_fsj  = re.compile(r'fsj ([0-9.]+)')

def parse_ciri_gtf(path):
    out = {}
    if not os.path.exists(path):
        return out
    with open(path) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            attrs = line.rstrip("\n").split("\t")[-1]
            m = re_circ.search(attrs)
            if not m:
                continue
            cid = m.group(1)
            b = re_bsj.search(attrs); f = re_fsj.search(attrs)
            if b and f:
                out[cid] = (float(b.group(1)), float(f.group(1)))
    return out

# ============== Per-sample consensus universe ==============
print("Reading per-sample BEDs for consensus detection ...")
consensus_per_sample = {}
for s in SAMPLES:
    ce2  = parse_ce2_ids(BASE / "circexplorer2" / s / f"{s}.bed")
    cirq = parse_ciri_ids(BASE / "ciriquant"    / s / f"{s}.bed")
    inter = ce2 & cirq
    consensus_per_sample[s] = inter
    print(f"  {s}: CE2 {len(ce2):>5}  CIRIquant {len(cirq):>5}  consensus {len(inter):>5}")

universe = sorted(set().union(*consensus_per_sample.values()))
print(f"\nUnion of per-sample consensus calls (pre-filter): {len(universe)} circRNAs")

# ============== BSJ + FSJ matrices from CIRIquant GTFs ==============
print("\nReading CIRIquant GTFs to get BSJ/FSJ counts ...")
bsj = pd.DataFrame(0.0, index=universe, columns=SAMPLES)
fsj = pd.DataFrame(0.0, index=universe, columns=SAMPLES)
bed_to_gtf = {c: bed_to_gtf_key(c) for c in universe}
gtf_to_bed = {v: k for k, v in bed_to_gtf.items()}

for s in SAMPLES:
    gtf = BASE / "ciriquant" / "intermediates" / s / s / f"{s}.gtf"
    rec = parse_ciri_gtf(gtf)
    n = 0
    for gtf_key, (b, f) in rec.items():
        cid = gtf_to_bed.get(gtf_key)
        if cid is None:
            continue
        bsj.loc[cid, s] = b
        fsj.loc[cid, s] = f
        n += 1
    print(f"  {s}: GTF records {len(rec):>5}  matched-to-universe {n:>5}")

# ============== Abundance filter on CIRIquant BSJ ==============
keep_mask = (bsj >= 2).sum(axis=1) >= 2
n_pre = len(universe); n_post = int(keep_mask.sum())
print(f"\nCIRIquant BSJ abundance filter (>= 2 reads in >= 2 samples): "
      f"{n_post:,} / {n_pre:,} ({100*n_post/n_pre:.1f}%)")

bsj_filt = bsj.loc[keep_mask].copy()
fsj_filt = fsj.loc[keep_mask].copy()

# ============== Annotation join ==============
print(f"\nJoining annotation from: {ANNOT}")
ann = pd.read_csv(ANNOT, sep="\t").set_index("circRNA")
# Split BED-style ID into chr/start/end/strand to write the same metadata columns
# that prior analyses use.
def split_circ(cid):
    chrom, rest = cid.split(":", 1)
    coords, strand = rest.rsplit(":", 1)
    s, e = coords.split("-")
    return chrom, int(s), int(e), strand

def write_matrix(df, name):
    rows = []
    for cid in df.index:
        chrom, s, e, strand = split_circ(cid)
        if cid in ann.index:
            sym  = ann.loc[cid, "gene_symbol"]
            gid  = ann.loc[cid, "gene_id"]
            ctyp = ann.loc[cid, "circ_type"]
        else:
            sym, gid, ctyp = "NA", "NA", "NA"
        rows.append([cid, sym, chrom, s, e, strand, ctyp, gid])
    meta_cols = ["circRNA","gene_symbol","chr","start","end","strand","circ_type","gene_id"]
    meta = pd.DataFrame(rows, columns=meta_cols).set_index("circRNA")
    out = meta.join(df, how="left").reset_index()
    out.to_csv(OUTDIR / name, sep="\t", index=False)
    print(f"  wrote {name}: {out.shape}")

print(f"\nWriting matrices ...")
write_matrix(bsj_filt, "bsj_matrix_CIRIquant_HnrnpM_PSD58.tsv")
write_matrix(fsj_filt, "fsj_matrix_CIRIquant_HnrnpM_PSD58.tsv")
print("\nDone.")
